export enum Env {
  NODE_ENV = 'NODE_ENV',
  SERVICE_NAME = 'SERVICE_NAME',
  SERVICE_HTTP_PORT = 'SERVICE_HTTP_PORT',
  SERVICE_HTTP_HOST = 'SERVICE_HTTP_HOST',
  SERVICE_HTTP_LOG_LEVEL = 'SERVICE_HTTP_LOG_LEVEL',
  SERVICE_CONSOLE_LOG = 'SERVICE_CONSOLE_LOG',
  SERVICE_FILE_LOG = 'SERVICE_FILE_LOG',
}
