export enum Env {
  NODE_ENV = 'NODE_ENV',
  SERVICE_NAME = 'SERVICE_NAME',
  SERVICE_PORT = 'SERVICE_PORT',
  SERVICE_HOST = 'SERVICE_HOST',
  SERVICE_HTTP_LOG_LEVEL = 'SERVICE_HTTP_LOG_LEVEL',
  LOG_IN_CONSOLE = 'LOG_IN_CONSOLE',
  LOG_IN_FILE = 'LOG_IN_FILE',
}
