import { throwError } from 'rxjs'

// import { IRpcException } from '@afrak-cpc-shared/shared-module'
import { Catch, ExceptionFilter, HttpException, Logger } from '@nestjs/common'
import { RpcException } from '@nestjs/microservices'

/**
 * Converting the exception model generated by the server to the specific model of the project.
 * @version 1.0
 */
@Catch(RpcException)
export class RpcExceptionFilter implements ExceptionFilter {
  private readonly logger = new Logger(RpcExceptionFilter.name)
  catch(
    exception: HttpException,
    // | IRpcException
    //TODO : irpc exception
  ) {
    this.logger.error(exception)
    switch (exception.constructor.name) {
      case 'IRpcException':
        return throwError(() => exception)
      default:
        return throwError(() => new RpcException(exception))
    }
  }
}
