version: '3.8'

services:
  webengage-api-butterfly:
    image: $IMAGE_TAG
    container_name: webengage-api-butterfly
    restart: always
    env_file:
      - .env
    ports:
      - '${SERVICE_DOCKER_PORT}:${SERVICE_HTTP_PORT}'
