[build]
  command = "npm run netlify:build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**/*"]
  external_node_modules = ["@nestjs/websockets", "ioredis", "@grpc/grpc-js", "@grpc/proto-loader", "mqtt", "nats", "amqplib", "kafkajs", "amqp-connection-manager", "class-transformer/storage", "class-transformer"]

# Redirect all requests to the serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

# Explicitly redirect API paths
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

# Test API endpoint
[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/api-test"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"

# Increase build-time memory limit
[build.processing]
  skip_processing = false

# Increase function timeout and memory
[functions.server]
  included_files = ["dist/**/*"]
  node_bundler = "esbuild" 